/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as CancellationRouteImport } from './routes/cancellation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ManagingTrusteeRouteImport } from './routes/managing-trustee'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SabhaRouteImport } from './routes/sabha'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VedaPatasalaRouteImport } from './routes/veda-patasala'
import { Route as VedaVaniRouteImport } from './routes/veda-vani'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const CancellationRoute = CancellationRouteImport.update({
  id: '/cancellation',
  path: '/cancellation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagingTrusteeRoute = ManagingTrusteeRouteImport.update({
  id: '/managing-trustee',
  path: '/managing-trustee',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SabhaRoute = SabhaRouteImport.update({
  id: '/sabha',
  path: '/sabha',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VedaPatasalaRoute = VedaPatasalaRouteImport.update({
  id: '/veda-patasala',
  path: '/veda-patasala',
  getParentRoute: () => rootRouteImport,
} as any)
const VedaVaniRoute = VedaVaniRouteImport.update({
  id: '/veda-vani',
  path: '/veda-vani',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/cancellation': typeof CancellationRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/gallery': typeof GalleryRoute
  '/managing-trustee': typeof ManagingTrusteeRoute
  '/privacy': typeof PrivacyRoute
  '/sabha': typeof SabhaRoute
  '/terms': typeof TermsRoute
  '/veda-patasala': typeof VedaPatasalaRoute
  '/veda-vani': typeof VedaVaniRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/cancellation': typeof CancellationRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/gallery': typeof GalleryRoute
  '/managing-trustee': typeof ManagingTrusteeRoute
  '/privacy': typeof PrivacyRoute
  '/sabha': typeof SabhaRoute
  '/terms': typeof TermsRoute
  '/veda-patasala': typeof VedaPatasalaRoute
  '/veda-vani': typeof VedaVaniRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/cancellation': typeof CancellationRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/gallery': typeof GalleryRoute
  '/managing-trustee': typeof ManagingTrusteeRoute
  '/privacy': typeof PrivacyRoute
  '/sabha': typeof SabhaRoute
  '/terms': typeof TermsRoute
  '/veda-patasala': typeof VedaPatasalaRoute
  '/veda-vani': typeof VedaVaniRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/cancellation'
    | '/contact'
    | '/donate'
    | '/gallery'
    | '/managing-trustee'
    | '/privacy'
    | '/sabha'
    | '/terms'
    | '/veda-patasala'
    | '/veda-vani'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/cancellation'
    | '/contact'
    | '/donate'
    | '/gallery'
    | '/managing-trustee'
    | '/privacy'
    | '/sabha'
    | '/terms'
    | '/veda-patasala'
    | '/veda-vani'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/cancellation'
    | '/contact'
    | '/donate'
    | '/gallery'
    | '/managing-trustee'
    | '/privacy'
    | '/sabha'
    | '/terms'
    | '/veda-patasala'
    | '/veda-vani'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  CancellationRoute: typeof CancellationRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  GalleryRoute: typeof GalleryRoute
  ManagingTrusteeRoute: typeof ManagingTrusteeRoute
  PrivacyRoute: typeof PrivacyRoute
  SabhaRoute: typeof SabhaRoute
  TermsRoute: typeof TermsRoute
  VedaPatasalaRoute: typeof VedaPatasalaRoute
  VedaVaniRoute: typeof VedaVaniRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancellation': {
      id: '/cancellation'
      path: '/cancellation'
      fullPath: '/cancellation'
      preLoaderRoute: typeof CancellationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/managing-trustee': {
      id: '/managing-trustee'
      path: '/managing-trustee'
      fullPath: '/managing-trustee'
      preLoaderRoute: typeof ManagingTrusteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sabha': {
      id: '/sabha'
      path: '/sabha'
      fullPath: '/sabha'
      preLoaderRoute: typeof SabhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veda-patasala': {
      id: '/veda-patasala'
      path: '/veda-patasala'
      fullPath: '/veda-patasala'
      preLoaderRoute: typeof VedaPatasalaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veda-vani': {
      id: '/veda-vani'
      path: '/veda-vani'
      fullPath: '/veda-vani'
      preLoaderRoute: typeof VedaVaniRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  CancellationRoute: CancellationRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  GalleryRoute: GalleryRoute,
  ManagingTrusteeRoute: ManagingTrusteeRoute,
  PrivacyRoute: PrivacyRoute,
  SabhaRoute: SabhaRoute,
  TermsRoute: TermsRoute,
  VedaPatasalaRoute: VedaPatasalaRoute,
  VedaVaniRoute: VedaVaniRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
